---
name: Buildpacks
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildpack-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack Build
        uses: dfreilich/pack-action@v2
        with:
          args: build ghcr.io/otaviof/nodejs-ex --builder="paketobuildpacks/builder:base"
